version: "3.6"

services:
  nginx:
    image: nginx:alpine
    container_name: ngrok_nginx
    volumes:
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
      - "./docker/webroot:/opt/html"
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - ngrok-network
  ngrok:
    build:
      context: .
    container_name: ngrok_ngrok
    restart: always
    volumes:
      - "./docker/webroot:/opt/html"
    environment:
      TZ: "Asia/Shanghai"
      DOMAIN: 'ng.adong.wiki'
      HTTPS: 8443
      HTTP: 8080
    ports:
      - "4443:4443"
      - "15672:8080"
    networks:
      - ngrok-network

networks:
  ngrok-network:
    name: ngrok_network
    ipam:
      config:
        - subnet: 172.10.0.0/16